name: content_block_parser_example
description: Demonstrates how to use the content_block_parser plugin.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12
  json_annotation: '>=4.8.1 <4.9.0'
  content_block_parser:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
